// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountCreationEmailForm: typeof import('./src/components/OnBoarding/AccountCreationEmailForm.vue')['default']
    AccountCreationPassword: typeof import("./src/components/OnBoarding/AccountCreationPassword.vue")["default"]
    AccountCreationPasswordForm: typeof import('./src/components/OnBoarding/AccountCreationPasswordForm.vue')['default']
    AccountCreationPasword: typeof import("./src/components/OnBoarding/AccountCreationPasword.vue")["default"]
    AppLogo: typeof import('./src/components/Common/AppLogo.vue')['default']
    AvatarUser: typeof import('./src/components/Common/AvatarUser.vue')['default']
    BarChart: typeof import("./src/components/UserDashboard/BarChart/BarChart.vue")["default"]
    BarChartPole: typeof import('./src/components/UserDashboard/BarChart/BarChartPole.vue')['default']
    BarChartWrapper: typeof import('./src/components/UserDashboard/BarChart/BarChartWrapper.vue')['default']
    ButtonForm: typeof import('./src/components/Common/ButtonForm.vue')['default']
    CampaningListForm: typeof import('./src/components/UserDashboard/CampaningListForm.vue')['default']
    CampaningListItem: typeof import('./src/components/UserDashboard/CampaningListItem.vue')['default']
    CardPanel: typeof import('./src/components/Common/CardPanel.vue')['default']
    ChartTimelineContent: typeof import('./src/components/UserDashboard/ChartTimeline/ChartTimelineContent.vue')['default']
    ChartTimelineItem: typeof import('./src/components/UserDashboard/ChartTimeline/ChartTimelineItem.vue')['default']
    ChartTimelineWrapper: typeof import('./src/components/UserDashboard/ChartTimeline/ChartTimelineWrapper.vue')['default']
    CheckboxForm: typeof import('./src/components/Common/CheckboxForm.vue')['default']
    ConnectAccountForm: typeof import('./src/components/OnBoarding/ConnectAccountForm.vue')['default']
    ConnectMoreServicesForm: typeof import('./src/components/OnBoarding/ConnectMoreServicesForm.vue')['default']
    DividerLine: typeof import('./src/components/Common/DividerLine.vue')['default']
    DropdownMenu: typeof import('./src/components/Common/DropdownMenu.vue')['default']
    FloatingPanel: typeof import('./src/components/Common/FloatingPanel.vue')['default']
    FloatingSwitchViewForm: typeof import('./src/components/UserDashboard/FloatingSwitchViewForm.vue')['default']
    HeaderDashboard: typeof import('./src/components/UserDashboard/HeaderDashboard.vue')['default']
    HeaderText: typeof import('./src/components/Common/HeaderText.vue')['default']
    IconSvg: typeof import('./src/components/Common/IconSvg.vue')['default']
    InputForm: typeof import('./src/components/Common/InputForm.vue')['default']
    LegendDescription: typeof import('./src/components/UserDashboard/LegendDescription.vue')['default']
    MenuList: typeof import('./src/components/Common/MenuList.vue')['default']
    OnBoardingLayout: typeof import('./src/components/Layouts/OnBoardingLayout.vue')['default']
    PopoverPanel: typeof import('./src/components/Common/PopoverPanel.vue')['default']
    ProgressBar: typeof import('./src/components/Common/ProgressBar.vue')['default']
    ProvidersListForm: typeof import('./src/components/UserDashboard/ProvidersListForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesNumber: typeof import('./src/components/UserDashboard/SalesNumber.vue')['default']
    ScrollbarPanel: typeof import('./src/components/Common/ScrollbarPanel.vue')['default']
    SelectForm: typeof import('./src/components/Common/SelectForm.vue')['default']
    SpinnerBar: typeof import('./src/components/Common/SpinnerBar.vue')['default']
    TagPin: typeof import('./src/components/Common/TagPin.vue')['default']
    TimelineContent: typeof import("./src/components/UserDashboard/ChartTimeline/TimelineContent.vue")["default"]
    TimelineItem: typeof import("./src/components/UserDashboard/ChartTimeline/TimelineItem.vue")["default"]
    TimelineWrapper: typeof import("./src/components/UserDashboard/ChartTimeline/TimelineWrapper.vue")["default"]
    UploadFile: typeof import('./src/components/Common/UploadFile.vue')['default']
    UserDashboardLayout: typeof import('./src/components/Layouts/UserDashboardLayout.vue')['default']
  }
}
