// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AccountCreationEmailForm: typeof import("./src/components/OnBoarding/AccountCreationEmailForm.vue")["default"];
    AccountCreationPassword: typeof import("./src/components/OnBoarding/AccountCreationPassword.vue")["default"];
    AccountCreationPasswordForm: typeof import("./src/components/OnBoarding/AccountCreationPasswordForm.vue")["default"];
    AccountCreationPasword: typeof import("./src/components/OnBoarding/AccountCreationPasword.vue")["default"];
    AppLogo: typeof import("./src/components/Common/AppLogo.vue")["default"];
    AvatarUser: typeof import("./src/components/Common/AvatarUser.vue")["default"];
    BarChart: typeof import("./src/components/UserDashboard/BarChart/BarChart.vue")["default"];
    BarChartDaysWeek: typeof import("./src/components/UserDashboard/BarChart/BarChartDaysWeek.vue")["default"];
    BarChartDaysWeekItem: typeof import("./src/components/UserDashboard/BarChart/BarChartDaysWeekItem.vue")["default"];
    BarChartPole: typeof import("./src/components/UserDashboard/BarChart/BarChartPole.vue")["default"];
    BarChartPoleContent: typeof import("./src/components/UserDashboard/BarChart/BarChartPoleContent.vue")["default"];
    BarChartPoleItem: typeof import("./src/components/UserDashboard/BarChart/BarChartPoleItem.vue")["default"];
    BarChartPoleLines: typeof import("./src/components/UserDashboard/BarChart/BarChartPoleLines.vue")["default"];
    BarChartPoleWrapper: typeof import("./src/components/UserDashboard/BarChart/BarChartPoleWrapper.vue")["default"];
    BarChartWeeks: typeof import("./src/components/UserDashboard/BarChart/BarChartWeeks.vue")["default"];
    BarChartWeeksItem: typeof import("./src/components/UserDashboard/BarChart/BarChartWeeksItem.vue")["default"];
    BarChartWrapper: typeof import("./src/components/UserDashboard/BarChart/BarChartWrapper.vue")["default"];
    ButtonForm: typeof import("./src/components/Common/ButtonForm.vue")["default"];
    CampaningListForm: typeof import("./src/components/UserDashboard/CampaningListForm.vue")["default"];
    CampaningListItem: typeof import("./src/components/UserDashboard/CampaningListItem.vue")["default"];
    CardPanel: typeof import("./src/components/Common/CardPanel.vue")["default"];
    ChartTimelineContent: typeof import("./src/components/UserDashboard/ChartTimeline/ChartTimelineContent.vue")["default"];
    ChartTimelineItem: typeof import("./src/components/UserDashboard/ChartTimeline/ChartTimelineItem.vue")["default"];
    ChartTimelineWeeks: typeof import("./src/components/UserDashboard/ChartTimeline/ChartTimelineWeeks.vue")["default"];
    ChartTimelineWeeksItem: typeof import("./src/components/UserDashboard/ChartTimeline/ChartTimelineWeeksItem.vue")["default"];
    ChartTimelineWrapper: typeof import("./src/components/UserDashboard/ChartTimeline/ChartTimelineWrapper.vue")["default"];
    CheckboxForm: typeof import("./src/components/Common/CheckboxForm.vue")["default"];
    CodeForm: typeof import("./src/components/Common/CodeForm.vue")["default"];
    CollectionAdsList: typeof import("./src/components/UserDashboard/Collection/CollectionAdsList.vue")["default"];
    CollectionBottomBar: typeof import("./src/components/UserDashboard/Collection/CollectionBottomBar.vue")["default"];
    CollectionHeader: typeof import("./src/components/UserDashboard/Collection/CollectionHeader.vue")["default"];
    CollectionProvidersList: typeof import("./src/components/UserDashboard/Collection/CollectionProvidersList.vue")["default"];
    CollectionSideItems: typeof import("./src/components/UserDashboard/Collection/CollectionSideItems.vue")["default"];
    CollectionTimeline: typeof import("./src/components/UserDashboard/Collection/CollectionTimeline.vue")["default"];
    CollectionTimelineContent: typeof import("./src/components/UserDashboard/Collection/CollectionTimelineContent.vue")["default"];
    CollectionTimelineItem: typeof import("./src/components/UserDashboard/Collection/CollectionTimelineItem.vue")["default"];
    CollectionWeeks: typeof import("./src/components/UserDashboard/Collection/CollectionWeeks.vue")["default"];
    CollectionWeeksItem: typeof import("./src/components/UserDashboard/Collection/CollectionWeeksItem.vue")["default"];
    ConnectAccountForm: typeof import("./src/components/OnBoarding/ConnectAccountForm.vue")["default"];
    ConnectMoreServicesFileSettingsForm: typeof import("./src/components/OnBoarding/ConnectMoreServicesFileSettingsForm.vue")["default"];
    ConnectMoreServicesForm: typeof import("./src/components/OnBoarding/ConnectMoreServicesForm.vue")["default"];
    DividerLine: typeof import("./src/components/Common/DividerLine.vue")["default"];
    DragDropElement: typeof import("./src/components/Common/DragDropElement.vue")["default"];
    DragElement: typeof import("./src/components/Common/DragElement.vue")["default"];
    DropdownMenu: typeof import("./src/components/Common/DropdownMenu.vue")["default"];
    DummyDragElement: typeof import("./src/components/Common/DummyDragElement.vue")["default"];
    FloatingPanel: typeof import("./src/components/Common/FloatingPanel.vue")["default"];
    FloatingSwitchViewForm: typeof import("./src/components/UserDashboard/FloatingSwitchViewForm.vue")["default"];
    HeaderDashboard: typeof import("./src/components/UserDashboard/HeaderDashboard.vue")["default"];
    HeaderText: typeof import("./src/components/Common/HeaderText.vue")["default"];
    IconSvg: typeof import("./src/components/Common/IconSvg.vue")["default"];
    InputForm: typeof import("./src/components/Common/InputForm.vue")["default"];
    LegendDescription: typeof import("./src/components/UserDashboard/LegendDescription.vue")["default"];
    MenuList: typeof import("./src/components/Common/MenuList.vue")["default"];
    ModalWindow: typeof import("./src/components/Common/ModalWindow.vue")["default"];
    MultiSelectForm: typeof import("./src/components/Common/MultiSelectForm.vue")["default"];
    NotificationMessage: typeof import("./src/components/Common/NotificationMessage.vue")["default"];
    OnBoardingLayout: typeof import("./src/components/Layouts/OnBoardingLayout.vue")["default"];
    PopoverPanel: typeof import("./src/components/Common/PopoverPanel.vue")["default"];
    ProgressBar: typeof import("./src/components/Common/ProgressBar.vue")["default"];
    ProvidersListForm: typeof import("./src/components/UserDashboard/ProvidersListForm.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SalesNumber: typeof import("./src/components/UserDashboard/SalesNumber.vue")["default"];
    ScrollbarPanel: typeof import("./src/components/Common/ScrollbarPanel.vue")["default"];
    SelectForm: typeof import("./src/components/Common/SelectForm.vue")["default"];
    SpinnerBar: typeof import("./src/components/Common/SpinnerBar.vue")["default"];
    TagPin: typeof import("./src/components/Common/TagPin.vue")["default"];
    TimelineContent: typeof import("./src/components/UserDashboard/ChartTimeline/TimelineContent.vue")["default"];
    TimelineItem: typeof import("./src/components/UserDashboard/ChartTimeline/TimelineItem.vue")["default"];
    TimelineWrapper: typeof import("./src/components/UserDashboard/ChartTimeline/TimelineWrapper.vue")["default"];
    TooltipMessage: typeof import("./src/components/Common/TooltipMessage.vue")["default"];
    UploadFile: typeof import("./src/components/Common/UploadFile.vue")["default"];
    UserDashboardDetialsLayout: typeof import("./src/components/Layouts/UserDashboardDetialsLayout.vue")["default"];
    UserDashboardLayout: typeof import("./src/components/Layouts/UserDashboardLayout.vue")["default"];
    ZoomScale: typeof import("./src/components/UserDashboard/ZoomScale.vue")["default"];
  }
}
