// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountCreationEmailForm: typeof import('./src/components/OnBoarding/AccountCreationEmailForm.vue')['default']
    AccountCreationPassword: typeof import('./src/components/OnBoarding/AccountCreationPassword.vue')['default']
    AccountCreationPasswordForm: typeof import('./src/components/OnBoarding/AccountCreationPasswordForm.vue')['default']
    AccountCreationPasword: typeof import('./src/components/OnBoarding/AccountCreationPasword.vue')['default']
    AppLogo: typeof import('./src/components/Common/AppLogo.vue')['default']
    ButtonForm: typeof import('./src/components/Common/ButtonForm.vue')['default']
    CardPanel: typeof import('./src/components/Common/CardPanel.vue')['default']
    ConnectAccountForm: typeof import('./src/components/OnBoarding/ConnectAccountForm.vue')['default']
    ConnectMoreServicesForm: typeof import('./src/components/OnBoarding/ConnectMoreServicesForm.vue')['default']
    DividerLine: typeof import('./src/components/Common/DividerLine.vue')['default']
    HeaderText: typeof import('./src/components/Common/HeaderText.vue')['default']
    IconSvg: typeof import('./src/components/Common/IconSvg.vue')['default']
    InputForm: typeof import('./src/components/Common/InputForm.vue')['default']
    OnBoardingLayout: typeof import('./src/components/Layouts/OnBoardingLayout.vue')['default']
    ProgressBar: typeof import('./src/components/Common/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinnerBar: typeof import('./src/components/Common/SpinnerBar.vue')['default']
    TagPin: typeof import('./src/components/Common/TagPin.vue')['default']
    UploadFile: typeof import('./src/components/Common/UploadFile.vue')['default']
  }
}
