version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./api:/app
      - ./api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      # - /app/vendor
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      MAILER_DSN: ${MAILER_DSN:-smtp://mailhog:1025}
    extra_hosts:
      - host.docker.internal:host-gateway
    user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"

  pwa:
    build:
      context: ./pwa
      target: dev
    volumes:
      - ./pwa:/app
    environment:
      WATCHPACK_POLLING: ${PWA_WATCHPACK_POLLING:-0}
      NODE_ENV: ${NODE_ENV:-development}
    user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"

  caddy:
    volumes:
      - ./api/public:/app/public:ro
      - ./api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      PWA_UPSTREAM: ${PWA_UPSTREAM:-pwa:5173}
      PHP_SOCKET: ${PHP_SOCKET:-php:9000}

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

