version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_ENV: prod

  caddy:
    environment:
      PWA_UPSTREAM: ${PWA_UPSTREAM:-pwa:443}
      PHP_SOCKET: ${PHP_SOCKET:-php:9000}

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
