app_password_reset:
    path: /onboarding/authentication/confirm-password-reset/{token}

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
